### ISSUE TITLE
Stop suppressing warnings with -Wno-cast-function-type

### ISSUE THREAD

**Issue by aalexand** [googleapis/cloud-profiler-nodejs#315] opened 2018-10-22 16:19 UTC
```
Mon Oct 22 15:22:36 UTC 2018: ++ node -e 'console.log(require('''./package.json''').version);'
Mon Oct 22 15:22:36 UTC 2018: + VERSION=0.2.2
Mon Oct 22 15:22:36 UTC 2018: + PROFILER=/cloud-profiler-nodejs/google-cloud-profiler-0.2.2.tgz
Mon Oct 22 15:22:36 UTC 2018: + TESTDIR=/test
Mon Oct 22 15:22:36 UTC 2018: + mkdir -p /test
Mon Oct 22 15:22:36 UTC 2018: + cp -r testing/busybench /test
Mon Oct 22 15:22:36 UTC 2018: + cd /test/busybench
Mon Oct 22 15:22:36 UTC 2018: + retry npm install --nodedir=/.nvm/versions/node/v10.12.0 /cloud-profiler-nodejs/google-cloud-profiler-0.2.2.tgz
Mon Oct 22 15:22:36 UTC 2018: + for i in {1..3}
Mon Oct 22 15:22:36 UTC 2018: + npm install --nodedir=/.nvm/versions/node/v10.12.0 /cloud-profiler-nodejs/google-cloud-profiler-0.2.2.tgz
Mon Oct 22 15:22:40 UTC 2018: In file included from ../../../nan/nan_new.h:189:0,
Mon Oct 22 15:22:40 UTC 2018: from ../../../nan/nan.h:222,
Mon Oct 22 15:22:40 UTC 2018: from ../bindings/sampling-heap-profiler.cc:19:
Mon Oct 22 15:22:40 UTC 2018: ../../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
Mon Oct 22 15:22:40 UTC 2018: ../../../nan/nan_implementation_12_inl.h:340:37: warning: ‘static v8::Local<v8::Value> v8::StringObject::New(v8::Local<v8::String>)’ is deprecated: Use Isolate* version [-Wdeprecated-declarations]
Mon Oct 22 15:22:40 UTC 2018: return v8::StringObject::New(value).As<v8::StringObject>();
Mon Oct 22 15:22:40 UTC 2018: ^
Mon Oct 22 15:22:40 UTC 2018: In file included from /.nvm/versions/node/v10.12.0/include/node/v8.h:26:0,
Mon Oct 22 15:22:40 UTC 2018: from /.nvm/versions/node/v10.12.0/include/node/v8-profiler.h:10,
Mon Oct 22 15:22:40 UTC 2018: from ../bindings/sampling-heap-profiler.cc:18:
Mon Oct 22 15:22:40 UTC 2018: /.nvm/versions/node/v10.12.0/include/node/v8.h:5053:37: note: declared here
Mon Oct 22 15:22:40 UTC 2018: static Local<Value> New(Local<String> value));
Mon Oct 22 15:22:40 UTC 2018: ^
Mon Oct 22 15:22:40 UTC 2018: /.nvm/versions/node/v10.12.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
Mon Oct 22 15:22:40 UTC 2018: declarator __attribute__((deprecated(message)))
Mon Oct 22 15:22:40 UTC 2018: ^~~~~~~~~~
Mon Oct 22 15:22:40 UTC 2018: In file included from ../bindings/sampling-heap-profiler.cc:19:0:
Mon Oct 22 15:22:40 UTC 2018: ../../../nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value>)’:
Mon Oct 22 15:22:40 UTC 2018: ../../../nan/nan.h:1066:53: warning: ‘v8::Local<v8::String> v8::Value::ToString() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
Mon Oct 22 15:22:40 UTC 2018: v8::Local<v8::String> string = from->ToString();
Mon Oct 22 15:22:40 UTC 2018: ^
Mon Oct 22 15:22:40 UTC 2018: In file included from /.nvm/versions/node/v10.12.0/include/node/v8-profiler.h:10:0,
Mon Oct 22 15:22:40 UTC 2018: from ../bindings/sampling-heap-profiler.cc:18:
Mon Oct 22 15:22:40 UTC 2018: /.nvm/versions/node/v10.12.0/include/node/v8.h:10040:15: note: declared here
Mon Oct 22 15:22:40 UTC 2018: Local<String> Value::ToString() const {
Mon Oct 22 15:22:40 UTC 2018: ^~~~~
Mon Oct 22 15:22:40 UTC 2018: In file included from ../bindings/sampling-heap-profiler.cc:19:0:
Mon Oct 22 15:22:40 UTC 2018: ../../../nan/nan.h:1080:74: warning: ‘int v8::String::WriteUtf8(char*, int, int*, int) const’ is deprecated: Use Isolate* version [-Wdeprecated-declarations]
Mon Oct 22 15:22:40 UTC 2018: length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
Mon Oct 22 15:22:40 UTC 2018: ^
Mon Oct 22 15:22:40 UTC 2018: In file included from /.nvm/versions/node/v10.12.0/include/node/v8.h:26:0,
Mon Oct 22 15:22:40 UTC 2018: from /.nvm/versions/node/v10.12.0/include/node/v8-profiler.h:10,
Mon Oct 22 15:22:40 UTC 2018: from ../bindings/sampling-heap-profiler.cc:18:
Mon Oct 22 15:22:40 UTC 2018: /.nvm/versions/node/v10.12.0/include/node/v8.h:2659:21: note: declared here
Mon Oct 22 15:22:40 UTC 2018: int WriteUtf8(char* buffer, int length = -1,
Mon Oct 22 15:22:40 UTC 2018: ^
Mon Oct 22 15:22:40 UTC 2018: /.nvm/versions/node/v10.12.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
Mon Oct 22 15:22:40 UTC 2018: declarator __attribute__((deprecated(message)))
Mon Oct 22 15:22:40 UTC 2018: ^~~~~~~~~~
Mon Oct 22 15:22:40 UTC 2018: ../bindings/sampling-heap-profiler.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE StartSamplingHeapProfiler(Nan::NAN_METHOD_ARGS_TYPE)’:
Mon Oct 22 15:22:40 UTC 2018: ../bindings/sampling-heap-profiler.cc:69:67: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
Mon Oct 22 15:22:40 UTC 2018: uint64_t sample_interval = info[0].As<Integer>()->Uint32Value();
Mon Oct 22 15:22:40 UTC 2018: ^
Mon Oct 22 15:22:40 UTC 2018: In file included from /.nvm/versions/node/v10.12.0/include/node/v8.h:26:0,
Mon Oct 22 15:22:40 UTC 2018: from /.nvm/versions/node/v10.12.0/include/node/v8-profiler.h:10,
Mon Oct 22 15:22:40 UTC 2018: from ../bindings/sampling-heap-profiler.cc:18:
Mon Oct 22 15:22:40 UTC 2018: /.nvm/versions/node/v10.12.0/include/node/v8.h:2477:47: note: declared here
Mon Oct 22 15:22:40 UTC 2018: V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
Mon Oct 22 15:22:40 UTC 2018: ^
Mon Oct 22 15:22:40 UTC 2018: /.nvm/versions/node/v10.12.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
Mon Oct 22 15:22:40 UTC 2018: declarator __attribute__((deprecated(message)))
Mon Oct 22 15:22:40 UTC 2018: ^~~~~~~~~~
Mon Oct 22 15:22:40 UTC 2018: ../bindings/sampling-heap-profiler.cc:70:59: warning: ‘int64_t v8::Value::IntegerValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
Mon Oct 22 15:22:40 UTC 2018: int stack_depth = info[1].As<Integer>()->IntegerValue();
Mon Oct 22 15:22:40 UTC 2018: ^
Mon Oct 22 15:22:40 UTC 2018: In file included from /.nvm/versions/node/v10.12.0/include/node/v8.h:26:0,
Mon Oct 22 15:22:40 UTC 2018: from /.nvm/versions/node/v10.12.0/include/node/v8-profiler.h:10,
Mon Oct 22 15:22:40 UTC 2018: from ../bindings/sampling-heap-profiler.cc:18:
Mon Oct 22 15:22:40 UTC 2018: /.nvm/versions/node/v10.12.0/include/node/v8.h:2476:46: note: declared here
Mon Oct 22 15:22:40 UTC 2018: V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
Mon Oct 22 15:22:40 UTC 2018: ^
Mon Oct 22 15:22:40 UTC 2018: /.nvm/versions/node/v10.12.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
Mon Oct 22 15:22:40 UTC 2018: declarator __attribute__((deprecated(message)))
Mon Oct 22 15:22:40 UTC 2018: ^~~~~~~~~~
Mon Oct 22 15:22:41 UTC 2018: In file included from ../../../nan/nan_new.h:189:0,
Mon Oct 22 15:22:41 UTC 2018: from ../../../nan/nan.h:222,
Mon Oct 22 15:22:41 UTC 2018: from ../bindings/time-profiler.cc:18:
Mon Oct 22 15:22:41 UTC 2018: ../../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
Mon Oct 22 15:22:41 UTC 2018: ../../../nan/nan_implementation_12_inl.h:340:37: warning: ‘static v8::Local<v8::Value> v8::StringObject::New(v8::Local<v8::String>)’ is deprecated: Use Isolate* version [-Wdeprecated-declarations]
Mon Oct 22 15:22:41 UTC 2018: return v8::StringObject::New(value).As<v8::StringObject>();
Mon Oct 22 15:22:41 UTC 2018: ^
Mon Oct 22 15:22:41 UTC 2018: In file included from /.nvm/versions/node/v10.12.0/include/node/v8.h:26:0,
Mon Oct 22 15:22:41 UTC 2018: from /.nvm/versions/node/v10.12.0/include/node/v8-profiler.h:10,
Mon Oct 22 15:22:41 UTC 2018: from ../bindings/time-profiler.cc:17:
Mon Oct 22 15:22:41 UTC 2018: /.nvm/versions/node/v10.12.0/include/node/v8.h:5053:37: note: declared here
Mon Oct 22 15:22:41 UTC 2018: static Local<Value> New(Local<String> value));
Mon Oct 22 15:22:41 UTC 2018: ^
Mon Oct 22 15:22:41 UTC 2018: /.nvm/versions/node/v10.12.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
Mon Oct 22 15:22:41 UTC 2018: declarator __attribute__((deprecated(message)))
Mon Oct 22 15:22:41 UTC 2018: ^~~~~~~~~~
Mon Oct 22 15:22:41 UTC 2018: In file included from ../bindings/time-profiler.cc:18:0:
Mon Oct 22 15:22:41 UTC 2018: ../../../nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value>)’:
Mon Oct 22 15:22:41 UTC 2018: ../../../nan/nan.h:1066:53: warning: ‘v8::Local<v8::String> v8::Value::ToString() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
Mon Oct 22 15:22:41 UTC 2018: v8::Local<v8::String> string = from->ToString();
Mon Oct 22 15:22:41 UTC 2018: ^
Mon Oct 22 15:22:41 UTC 2018: In file included from /.nvm/versions/node/v10.12.0/include/node/v8-profiler.h:10:0,
Mon Oct 22 15:22:41 UTC 2018: from ../bindings/time-profiler.cc:17:
Mon Oct 22 15:22:41 UTC 2018: /.nvm/versions/node/v10.12.0/include/node/v8.h:10040:15: note: declared here
Mon Oct 22 15:22:41 UTC 2018: Local<String> Value::ToString() const {
Mon Oct 22 15:22:41 UTC 2018: ^~~~~
Mon Oct 22 15:22:41 UTC 2018: In file included from ../bindings/time-profiler.cc:18:0:
Mon Oct 22 15:22:41 UTC 2018: ../../../nan/nan.h:1080:74: warning: ‘int v8::String::WriteUtf8(char*, int, int*, int) const’ is deprecated: Use Isolate* version [-Wdeprecated-declarations]
Mon Oct 22 15:22:41 UTC 2018: length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
Mon Oct 22 15:22:41 UTC 2018: ^
Mon Oct 22 15:22:41 UTC 2018: In file included from /.nvm/versions/node/v10.12.0/include/node/v8.h:26:0,
Mon Oct 22 15:22:41 UTC 2018: from /.nvm/versions/node/v10.12.0/include/node/v8-profiler.h:10,
Mon Oct 22 15:22:41 UTC 2018: from ../bindings/time-profiler.cc:17:
Mon Oct 22 15:22:41 UTC 2018: /.nvm/versions/node/v10.12.0/include/node/v8.h:2659:21: note: declared here
Mon Oct 22 15:22:41 UTC 2018: int WriteUtf8(char* buffer, int length = -1,
Mon Oct 22 15:22:41 UTC 2018: ^
Mon Oct 22 15:22:41 UTC 2018: /.nvm/versions/node/v10.12.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
Mon Oct 22 15:22:41 UTC 2018: declarator __attribute__((deprecated(message)))
Mon Oct 22 15:22:41 UTC 2018: ^~~~~~~~~~
Mon Oct 22 15:22:41 UTC 2018: ../bindings/time-profiler.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE SetSamplingInterval(Nan::NAN_METHOD_ARGS_TYPE)’:
Mon Oct 22 15:22:41 UTC 2018: ../bindings/time-profiler.cc:89:48: warning: ‘int64_t v8::Value::IntegerValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
Mon Oct 22 15:22:41 UTC 2018: int us = info[0].As<Integer>()->IntegerValue();
Mon Oct 22 15:22:41 UTC 2018: ^
Mon Oct 22 15:22:41 UTC 2018: In file included from /.nvm/versions/node/v10.12.0/include/node/v8.h:26:0,
Mon Oct 22 15:22:41 UTC 2018: from /.nvm/versions/node/v10.12.0/include/node/v8-profiler.h:10,
Mon Oct 22 15:22:41 UTC 2018: from ../bindings/time-profiler.cc:17:
Mon Oct 22 15:22:41 UTC 2018: /.nvm/versions/node/v10.12.0/include/node/v8.h:2476:46: note: declared here
Mon Oct 22 15:22:41 UTC 2018: V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
Mon Oct 22 15:22:41 UTC 2018: ^
Mon Oct 22 15:22:41 UTC 2018: /.nvm/versions/node/v10.12.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
Mon Oct 22 15:22:41 UTC 2018: declarator __attribute__((deprecated(message)))
Mon Oct 22 15:22:41 UTC 2018: ^~~~~~~~~~
Mon Oct 22 15:22:41 UTC 2018: npm notice created a lockfile as package-lock.json. You should commit this file.
Mon Oct 22 15:22:41 UTC 2018: npm WARN @0.0.0 No description
Mon Oct 22 15:22:41 UTC 2018: npm WARN @0.0.0 No repository field.
Mon Oct 22 15:22:41 UTC 2018: 
Mon Oct 22 15:22:41 UTC 2018: + return 0
Mon Oct 22 15:22:41 UTC 2018: + retry npm install
Mon Oct 22 15:22:41 UTC 2018: + for i in {1..3}
Mon Oct 22 15:22:41 UTC 2018: + npm install
Mon Oct 22 15:22:47 UTC 2018: npm WARN lifecycle @0.0.0~prepare: cannot run in wd @0.0.0 npm run compile (wd=/test/busybench)
Mon Oct 22 15:22:47 UTC 2018: npm WARN @0.0.0 No description
Mon Oct 22 15:22:47 UTC 2018: npm WARN @0.0.0 No repository field.
```

**Comment by aalexand** [comment] 2018-10-22 16:28
@nolanmar511 Ah, thanks, yes it was a mistake.

**Comment by nolanmar511** [comment] 2018-10-23 19:28
The ones originating from our files should be fixed by #318.

Most of these we need NAN to address (https://github.com/nodejs/nan/issues/810)

**Comment by BrianChristie** [comment] 2018-11-20 10:17
Can we get a release made with at least the fixes from https://github.com/googleapis/cloud-profiler-nodejs/pull/318 while waiting for NAN to address the remaining issues?

**Comment by nolanmar511** [comment] 2018-11-20 20:54
Thanks!
We just released 0.2.3!

**Comment by nolanmar511** [comment] 2018-12-10 15:31
https://github.com/nodejs/nan/issues/810 has been fixed, but not released since that fix. 

I asked on that issue for a new release of NAN.

**Comment by nolanmar511** [comment] 2019-01-09 20:52
With latest version of NAN installed, no deprecation warnings appear on master. 

Marking this as fixed.

**Comment by aalexand** [comment] 2019-01-09 21:44
@nolanmar511 Are prober logs also free of deprecation warnings now?

**Comment by nolanmar511** [comment] 2019-01-09 22:10
Still seeing the deprecation warnings in prober logs. 

I think we'd have to do a release.
The latest release uses an 2.11.1, and the necessary fixes weren't all present in nan until 2.12.1

**Comment by nolanmar511** [comment] 2019-01-28 17:37
Installing the latest version of `@google-cloud/profiler` with 10.12.0 (or with 10.15.0) does not have any deprecation warnings. 

Closing this.

**Comment by nolanmar511** [comment] 2019-01-28 18:06
Re-opening. 

I still see warnings in our prober.

**Comment by nolanmar511** [comment] 2019-02-25 18:30
I reproduced an an ubuntu GCE instance. For reference, here are deprecation warnings:

```
make: Entering directory '/home/nolanmar/tmp/node_modules/@google-cloud/profiler/build'
  CXX(target) Release/obj.target/google_cloud_profiler/bindings/profiler.o
In file included from ../bindings/profiler.cc:18:
../../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../../nan/nan.h:2232:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
                                                              ^
In file included from ../../../nan/nan.h:53,
                 from ../bindings/profiler.cc:18:
../bindings/profiler.cc: At global scope:
/home/nolanmar/.node-gyp/10.15.1/include/node/node.h:570:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/home/nolanmar/.node-gyp/10.15.1/include/node/node.h:604:3: note: in expansion of macro ‘NODE_MODULE_X’
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../bindings/profiler.cc:189:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(google_cloud_profiler, InitAll);
 ^~~~~~~~~~~
In file included from /home/nolanmar/.node-gyp/10.15.1/include/node/v8-profiler.h:10,
                 from ../bindings/profiler.cc:17:
/home/nolanmar/.node-gyp/10.15.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/nolanmar/.node-gyp/10.15.1/include/node/node_object_wrap.h:85:78:   required from here
/home/nolanmar/.node-gyp/10.15.1/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nolanmar/.node-gyp/10.15.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../../nan/nan_object_wrap.h:66:61:   required from here
/home/nolanmar/.node-gyp/10.15.1/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
```

**Comment by nolanmar511** [comment] 2019-02-26 19:20
Re-purposing this issue to be about removing the suppression of warnings added in #424 .

**Comment by nolanmar511** [comment] 2019-03-04 21:44
Removed from Beta hotlist, since this issue has been re-purposed and original deprecation warnings no longer appear.

**Comment by nolanmar511** [comment] 2019-05-15 20:57
Marking this as fixed since native component is now in pprof module.
I filed https://github.com/google/pprof-nodejs/pull/63 there.

**Closed by nolanmar511** 2019-05-15 20:57 UTC
Labels: type: cleanup
