### ISSUE TITLE
git clone is not retried properly?

### ISSUE THREAD

**Issue by aalexand** [googleapis/cloud-profiler-nodejs#328] opened 2018-11-08 03:42 UTC
Saw failure http://sponge/17b91230-680d-4878-ba61-ca9cb0223d39 today, with the errors below. Looks like the first git clone had some error (it's not in the log, perhaps we redirect all of the output from git clone to /dev/null?) but the future retries failed because the directory cloud-profiler-nodejs already existed. This should be retried better.

```
Thu Nov  8 01:21:49 UTC 2018: +++ dirname /.nvm/versions/node/v8.12.0/bin/node
Thu Nov  8 01:21:49 UTC 2018: ++ dirname /.nvm/versions/node/v8.12.0/bin
Thu Nov  8 01:21:49 UTC 2018: + NODEDIR=/.nvm/versions/node/v8.12.0
Thu Nov  8 01:21:49 UTC 2018: + retry git clone https://github.com/googleapis/cloud-profiler-nodejs.git
Thu Nov  8 01:21:49 UTC 2018: + for i in {1..3}
Thu Nov  8 01:21:49 UTC 2018: + git clone https://github.com/googleapis/cloud-profiler-nodejs.git
Thu Nov  8 01:21:49 UTC 2018: fatal: destination path 'cloud-profiler-nodejs' already exists and is not an empty directory.
Thu Nov  8 01:21:49 UTC 2018: + for i in {1..3}
Thu Nov  8 01:21:49 UTC 2018: + git clone https://github.com/googleapis/cloud-profiler-nodejs.git
Thu Nov  8 01:21:49 UTC 2018: fatal: destination path 'cloud-profiler-nodejs' already exists and is not an empty directory.
Thu Nov  8 01:21:49 UTC 2018: + for i in {1..3}
Thu Nov  8 01:21:49 UTC 2018: + git clone https://github.com/googleapis/cloud-profiler-nodejs.git
Thu Nov  8 01:21:49 UTC 2018: fatal: destination path 'cloud-profiler-nodejs' already exists and is not an empty directory.
Thu Nov  8 01:21:49 UTC 2018: + return 1
Thu Nov  8 01:21:49 UTC 2018: ++ sleep 300
```

**Comment by JustinBeckwith** [comment] 2019-05-13 20:05
Greetings folks!  This one has sat around for a while, and fell out of SLO.  Could someone take a look?  @nolanmar511 @aalexand

**Comment by nolanmar511** [comment] 2019-05-13 20:10
We have a matching issue internally. 
Going to close this in favor of internal issue. 

It's also not a bug, so much as cleanup.

**Closed by nolanmar511** 2019-05-13 20:10 UTC
Labels: :rotating_light:, priority: p2, type: cleanup
